### ISSUE TITLE
Add support for Windows 10 Native SSH agent

### ISSUE THREAD

**Issue by ncw** [xanzy/ssh-agent#5]
I use this library in rclone (thank you very much) for windows ssh support.

I recently had a request https://github.com/ncw/rclone/issues/2988 for adding support for "Windows 10 native ssh-agent".

According to one of the posts on that issue 

> It uses a Named Pipe located at `\\.\pipe\openssh-ssh-agent`

Could this library be tweaked to allow that as well as pagent?

**Comment by svanharmelen** [comment]
Thanks for opening this issue @ncw! I think it should be possible to add support for that, but I don't have access to a Windows 10 VM. So I need to have a look how I can facilitate that in order to be able to test and confirm that it works as expected.

**Comment by ncw** [comment]
You can download an eval Windows 10 VM from microsoft: https://developer.microsoft.com/en-us/windows/downloads/virtual-machines valid for 30 days.

**Comment by svanharmelen** [comment]
Hi @ncw! I'm sorry I never got back to this issue and noticed you just opened a new issue. I switched jobs (in May) in between these two issues which is probably why it fell off my radar.

I'm going to see if I can make some time for both these issues to solve them in one go. Feel free to ping me as a remainder if you don't hear back from me within a week or two!

**Comment by ncw** [comment]
The other issue is a similar but different request!

Thank you for working on this - it is a really useful library :-)  And no pressure!

**Comment by svanharmelen** [comment]
@ncw I think @ngyuki just added the required bits to solve this issue, right? Sorry I didn't get to it, but glad @ngyuki did 👍🏻 If you can confirm this solves this issue, then feel free to close it. Thanks.

**Comment by ncw** [comment]
That looks like just the thing.

I'll have a go and report back - thank you :-)

**Comment by svanharmelen** [comment]
It's been a while, so closing this one assuming it's solved by PR #7
