### ISSUE TITLE
Update dependencies, issue on Mac M1 (arm64)

### ISSUE THREAD

**Issue by mories76** [xanzy/ssh-agent#8]
Hi Sander,

I came across the following error message, more than a few times ;-)
```verifying go.mod: github.com/xanzy/ssh-agent@v0.3.0/go.mod: cannot authenticate record data in server response```

Please forgive me if I draw the wrong conclusion, just started Go programming for a terraform provider so this is all pretty new to me.

But, I am on a Mac M1 (darwin/arm64) I came across the same error message wether is was during the go get of the terraform-provider-sdk v2.7.0, terraform-exec or the install of goreleaser.
I think it al comes down to the dependency off ssh-agent on go-winio v0.4.14 (see error messages below)
From version >= v0.4.17 all goes well and the go-winio installs without any issues. 

```go install github.com/goreleaser/goreleaser@latest.  
go install github.com/goreleaser/goreleaser@latest: github.com/goreleaser/goreleaser@none updating to. 
	github.com/goreleaser/goreleaser@v0.174.1 requires. 
	github.com/goreleaser/nfpm/v2@v2.6.0 requires. 
	github.com/go-git/go-git/v5@v5.3.0 requires. 
	github.com/xanzy/ssh-agent@v0.3.0: verifying go.mod: github.com/xanzy/ssh-agent@v0.3.0/go.mod: cannot 
authenticate record data in server response```

```go get github.com/Microsoft/go-winio@v0.4.14
# github.com/Microsoft/go-winio/pkg/guid
/Users/me/go/pkg/mod/github.com/!microsoft/go-winio@v0.4.14/pkg/guid/guid.go:47:11: undefined: windows.GUID```

**Comment by svanharmelen** [comment]
Can you check/confirm that PR #9 solves the issues you are having before I merge it?

**Comment by mories76** [comment]
I have checked with the commit from PR #9.
And it works a expected.
```
go get github.com/xanzy/ssh-agent/@674c62c9d1f7a48673b6089cd5e9be9b3ba4c7c7
go: downloading github.com/xanzy/ssh-agent v0.3.1-0.20210804131906-674c62c9d1f7
```

**Comment by svanharmelen** [comment]
Thanks! Then I'll go ahead and merge the PR and tag a release...
